system:
  url-prefix: api
  api-version: v1
  port: 10000
  connect-timeout: 10
  rate-limit-max: 200

mysql:
  uri: 'root:haotianhuyu.wechat@tcp(43.139.15.105:3306)/md_media_wechat?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true&loc=Local&timeout=10000ms'
  table-prefix: md
  no-sql: false
  init-data: true
  transaction: true


redis:
  uri: 'redis://127.0.0.1:6379/0'
  enable: true
  enable-binlog: true


logs:
  # logger category(zap/logrus, default logrus)
  category: logrus
  # logger level(4:Info 5:Debug, 0<=level<=6, refer to go-helper log.level)
  level: 4
  # normal text or json str
  json: false
  line-num:
    # disable line num
    disable: false
    # line num level(package path level)
    level: 1
    # keep logger source dir
    source: false
    # keep logger version
    version: true
  # operation log context key
  operation-key: operation_log_response
  # allow users to delete operation logs
  operation-allowed-to-delete: false